votaciones/applications/users/urls.py
from django.urls import path

from . import views
app_name = 'users_app'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login-user'),
    path('logout/', views.LogoutView.as_view(), name='logout-user'),
]

votaciones/applications/votantes/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "votante_app"
urlpatterns = [
    path('bloqueo/', views.VerificarVotante.as_view(), name='verificacion-votante'),# se debe borrar el indexRaiz y dejar solo '' raiz
    path('eleccionCandidato/<cc>/', views.EleccionCandidato.as_view(), name='eleccion-votante'),
    path('error/', views.ErrorVotante.as_view(), name='error-votante'),
    path('agradecimiento/', views.agradecimientoVotante.as_view(), name='agradecimiento-votante'),
    path('reporte/', views.reporteVotacion.as_view(), name='reporte-votos'),
    path('reporte-directivo/', views.reporteVotacionDirectivo.as_view(), name='reporte-directivo'),
    path('reporte-administrativo/', views.reporteVotacionAdministrativo.as_view(), name='reporte-administrativo'),
    path('tabla/', views.TablaVotantesView.as_view(), name='tabla-votos'),
    path('', views.IndexTemporal.as_view(), name='temporal-index'), # esta se debe quitar, al momento de votar
]

votaciones/votaciones/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.votantes.urls')),
    path('', include('applications.users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

votaciones/applications/votantes/models.py
from email.policy import default
from django.db import models
from django.core.validators import RegexValidator


# Create your models here.
phone_regex = RegexValidator(regex=r'^\+?1?\d{5,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

class tipo_candidato(models.Model):
    type_candidate = models.CharField('Tipo de candidato', max_length=30)
    
    class Meta:
        verbose_name = "Tipo de Candidato"
        verbose_name_plural = "Tipos de candidato"

    def __str__(self):
        return self.type_candidate
class Votantes(models.Model):
    cedula = models.CharField("Numero de identificación", validators=[phone_regex], max_length=15, primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido  = models.CharField(max_length=50)
    email = models.EmailField(blank=True,null=True)
    estado_voto = models.BooleanField(default=False)
    tipo_candidato = models.ForeignKey(tipo_candidato, on_delete=models.CASCADE, related_name = 'votante_tipo_candidato')
    
    class Meta:
        verbose_name = "Votante"
        verbose_name_plural = "Votantes"

    def __str__(self):
        return self.nombre + ' ' + self.apellido + ' ' + self.cedula

votaciones/applications/votantes/forms.py
from django import forms
from django.forms.widgets import TextInput,NumberInput,EmailInput
from .models import Votantes

class VerificarVotanteForm(forms.ModelForm):
    class Meta:
        model = Votantes
        fields = ("cedula","email")
        widgets = {
            'cedula': NumberInput(attrs={'placeholder': 'Cédula'}),
            'email':  EmailInput(attrs={'placeholder':'Correo Electrónico','required':True})
        }

votaciones/applications/votantes/views.py
import datetime
import numpy as np
from django.db import IntegrityError
from django.urls.base import reverse_lazy
from django.shortcuts import render
from django.views.generic.edit import  FormView
from django.views.generic import ListView,TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import VerificarVotanteForm
# Create your views here.
from .models import Votantes, tipo_candidato
from applications.candidatos.models import Candidato,eleccion




class VerificarVotante(FormView):
    template_name = 'eleccion.html'
    form_class = VerificarVotanteForm
    success_url = 'candidatos.html'

    def post(self,request,*args, **kwargs):
        cedula_user =request.POST['cedula']
        email_user = request.POST['email']
        try:
            user = Votantes.objects.get(cedula=cedula_user)
            if user:
                if user.estado_voto==True:
                    message = 'El usuario registrado con la cedula #'+ '   ' + user.cedula+ '  '+' ya ha realizado la votación, si no fuiste tú'
                    return render(request,'error.html', {'message_error': message})
                else:
                    if user.email.strip().lower()==email_user.strip().lower():
                        return HttpResponseRedirect(reverse('votante_app:eleccion-votante',kwargs={'cc':user.cedula}))
                    else:
                        message = 'Lo sentimos usted no brindo las credenciales correctas, verificar cédula y correo electrónico.'
                        return render(request,'error.html', {'message_error': message})
        except ObjectDoesNotExist:
                    return render(
                        request,
                        'error.html',
                        {'message_error': 'Lo sentimos el numero de cedula  no se encuntra registrado, comunicarse con votacionesrepresentantes2022@gmail.com para más información'}
                        )
        return super().post(request,*args,**kwargs)

    def form_valid(self, VerificarVotanteForm):
        return super().form_valid(VerificarVotanteForm)

class ErrorVotante(TemplateView):
    template_name='error.html'

class agradecimientoVotante(TemplateView):
    template_name='gracias.html'


class EleccionCandidato(ListView):
    template_name = 'candidatos.html'
    context_object_name = 'candidatos'
    queryset = Candidato.objects.all().order_by('id')

    def get_context_data(self, **kwargs):
            context = super(EleccionCandidato,self).get_context_data(**kwargs)
            try:
                user = Votantes.objects.get(cedula=self.kwargs['cc'])
                if user:
                    candidatos = Candidato.objects.filter(tipo_candidato_id=user.tipo_candidato.id)
                    context["candidatos"] = candidatos
                    context["user"] = user
                else:
                    context["mensaje"] = "No cuenta con los privilegios para acceder"
            except ObjectDoesNotExist:
                context["mensaje"] = "No cuenta con los privilegios para acceder"
            return context



    def post(self,request,*args,**kwargs):
        elector = request.POST['cc']
        elector = Votantes.objects.get(cedula=elector)
        elector.estado_voto=True
        elector.save()
        candidato_seleccionado = request.POST['candi']
        print('candi 1', candidato_seleccionado)
        candidato_elegido = Candidato.objects.get(id=candidato_seleccionado)
        print('candi 2', candidato_elegido)
        try:
            voto = eleccion.objects.create(
                candidato=candidato_elegido,
                votante=elector
            )
        except IntegrityError:
            return  HttpResponseRedirect(reverse('votante_app:error-votante'))
        return  HttpResponseRedirect(reverse('votante_app:agradecimiento-votante'))



class reporteVotacion(LoginRequiredMixin,TemplateView):
    template_name='jurados/reporte.html'
    login_url = reverse_lazy('users_app:login-user')

    def  get_votos_candidato(self):
        total_votos = eleccion.objects.values(
            'candidato_id',
        ).annotate(data=Count('candidato_id')).filter(candidato__tipo_candidato=2).order_by('candidato_id')
        return total_votos

    def get_votos_candidate_for_hour(self):
        #fec='2021-07-11'
        #fecha = datetime.datetime.strptime(fec,"%Y-%m-%d").date()
        cantVotosHora=[]
        ArrayVotosCandidato1=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato2=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato3=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato4=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato5=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato6=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato7=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato8=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato9=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato10=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato11=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato12=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato13=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato14=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato15=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato16=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato17=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato18=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato19=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidato20=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        ArrayVotosCandidatosDocentes= np.zeros((20,24))
        #ArrayVotosCandidatosDocentes[29][23]=1

        for i in range(23):
            hora1=str(i)+':00:00'
            hora2=str(i)+':59:59'
            """votosHora= eleccion.objects.values('candidato_id').filter(
                created__time__range=(hora1,hora2),
                created__date=fecha).annotate(
                    data=Count('candidato_id'
                            )
                    )"""
            votosHora= eleccion.objects.values('candidato_id').filter(
            created__time__range=(hora1,hora2),candidato__tipo_candidato=2).annotate(
                data=Count('candidato_id')
                )
            if votosHora.exists():
                for j in range(len(votosHora)):
                    #print(j, votosHora[j]['candidato_id'])
                    if votosHora[j]['candidato_id']>0:
                        ArrayVotosCandidatosDocentes[votosHora[j]['candidato_id']-1][i] = votosHora[j]['data']
                    else:
                        ArrayVotosCandidatosDocentes[votosHora[j]['candidato_id']][i] = votosHora[j]['data']
                        #print('este es el array de 0', ArrayVotosCandidatosDocentes[0])
                    
                    """if votosHora[j]['candidato_id']==1:
                        ArrayVotosCandidato1[i]=votosHora[j]['data']
                    #if votosHora[j]['candidato_id']!=1:
                     #   ArrayVotosCandidato1.append(0)

                    if votosHora[j]['candidato_id']==2:
                        ArrayVotosCandidato2[i]=votosHora[j]['data']
                    #if votosHora[j]['candidato_id']!=2:
                    #    ArrayVotosCandidato2.append(0)

                    if votosHora[j]['candidato_id']==3:
                        ArrayVotosCandidato3[i]=votosHora[j]['data']
                        print('hola RRR')
                    #if votosHora[j]['candidato_id']!=3:
                    #    ArrayVotosCandidato3.append(0)

                    if votosHora[j]['candidato_id']==4:
                        ArrayVotosCandidato4[i]=votosHora[j]['data']
                    #if votosHora[j]['candidato_id']!=4:
                    #    ArrayVotosCandidato4.append(0)

                    if votosHora[j]['candidato_id']==5:
                        ArrayVotosCandidato5[i]=votosHora[j]['data']
                    #if votosHora[j]['candidato_id']!=5:
                    #    ArrayVotosCandidato5.append(0)

            else:
                ArrayVotosCandidato1[i]=0
                ArrayVotosCandidato2[i]=0
                ArrayVotosCandidato3[i]=0
                ArrayVotosCandidato4[i]=0
                ArrayVotosCandidato5[i]=0
        print('lista 1 ', ArrayVotosCandidato1)
        print('lista 2 ', ArrayVotosCandidato2)
        print('lista 3 ', ArrayVotosCandidato3)
        print('lista 4 ', ArrayVotosCandidato4)
        print('lista 5 ', ArrayVotosCandidato5)
        print(ArrayVotosCandidatosDocentes,'\\\\\**&&&')
        print(ArrayVotosCandidatosDocentes[29][19],'\\\\\**&&&')
        """
        ListasVotosPorCandidato = [ArrayVotosCandidato1,ArrayVotosCandidato2,ArrayVotosCandidato3,ArrayVotosCandidato4,ArrayVotosCandidato5]
        return ArrayVotosCandidatosDocentes

    def get_context_data(self, **kwargs):
        total_parcial = eleccion.objects.all().count()
        context = super().get_context_data(**kwargs)
        context ['panel'] = 'Panel de Administrador'
        lista_votos=[]
        porcentaje_votosPie=[]
        serieVotoshora=[]
        votosHoraCandidato1=[]
        votosHoraCandidato2=[]
        votosHoraCandidato3=[]
        votosHoraCandidato4=[]
        votosHoraCandidato5=[]
        votosHoraCandidato6=[]
        votosHoraCandidato7=[]
        votosHoraCandidato8=[]

votaciones/templates/jurados/login.html
{% extends "base.html" %} {% block content %}

<div id="a-login-container">
  <div id="a-login-card">
    <div id="a-login-left">
      {% load static %}
      <img src="{% static 'images/logo/votaciones.svg' %}" />
      <br />
      <h4>Iniciar sesión</h4>
      <form method="post">
        {% csrf_token %} {{form.as_p}}
        <br />
        <button class="a-main-btn" type="submit">Acceder</button>
        <br />
      </form>
    </div>
    <div id="a-login-right">
      {% load static %}
      <img src="{% static 'images/auth/login.png' %}" alt="" />
    </div>
  </div>
  {% load static %}
  <img src="{% static 'images/logo/villavo-white.svg' %}" alt="" height="50" id="a-login-logo-img"/>
</div>

{% endblock content %}

votaciones/templates/jurados/reporte.html
{% extends 'base.html' %} {% block head %} {% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
<script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/drilldown.js' %}"></script>

<script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock head %} {% block content %}

<div id="a-report-container">
    <!-- SIDEBAR -->
    <div class="a-sidebar-container">
        {% load static %}
        <a class="a-sidebar-icon active" href="{% url 'votante_app:reporte-votos' %}" id="docente" >
            <abbr title="Reporte Docente"> <img src="{% static 'images/report-icon.svg' %}" /></abbr>.
           
        </a>
        <a class="a-sidebar-icon " href="{% url 'votante_app:reporte-directivo' %} " id="directivo" >
            <abbr title="Reporte Directivo Docente"> <img src="{% static 'images/report-icon.svg' %}" /></abbr>.
        </a>
        <a class="a-sidebar-icon " href="{% url 'votante_app:reporte-administrativo' %}" id="administrativo" >
            <abbr title="Reporte Administrativo"> <img src="{% static 'images/report-icon.svg' %}" /></abbr>.
        </a>
        <a class="a-sidebar-icon" href="{% url 'votante_app:tabla-votos' %}">
            <img src="{% static 'images/users-icon.svg' %}" />
        </a>
    </div>

    <div class="a-main-container">
        <!-- NAVBAR -->
        <nav class="navbar navbar-dark">
            <div class="container-fluid">
                {% load static %}
                <img src="{% static 'images/logo/villavo-white.svg' %}" alt="" height="30" />

                <form class="d-flex">
                    <a href="{% url 'users_app:logout-user' %}" class="a-icon-text-btn" type="button">
                        <div class="a-icon-btn">
                            <img src="{% static 'images/logout.svg' %}" alt="" />
                        </div>
                        Salir
                    </a>
                </form>
            </div>
        </nav>

        <!-- MAIN CONTAINER -->
        <div id="a-charts-container">
            <!-- ROW -->
            <div id="a-row">
                <div class="a-chart-figure">
                    <figure class="highcharts-figure">
                        <div id="container"></div>
                    </figure>
                </div>
                <div class="a-separator"></div>
                <div class="a-chart-figure">
                    <figure class="highcharts-figure">
                        <div id="container3"></div>
                    </figure>
                </div>
            </div>
            <!-- ROW -->
            <div id="a-horizontal-chart" class="a-chart-figure">
                <figure class="highcharts-figure">
                    <div id="container2"></div>
                </figure>
            </div>

            <!-- FOOTER -->

            <div class="a-footer">
                <span>
          Desarrollado por la Dirección de Sistemas Tecnológicos e
          Informáticos</span
        >
        <span> Secretaria de las TIC- Villavicencio Cambia Contigo</span>
            </div>
        </div>
    </div>
</div>

<script>
    Highcharts.setOptions({
        colors: ['#00d784', '#2b5ac4', '#00b7ff','#d90024', '#fdc30f', '#ca00d9']
    });

    Highcharts.chart('container', {
        chart: {
            type: 'column',
            backgroundColor: '#f4f3f8',
        },
        title: {
            text: 'Tabla de Votación'
        },
        subtitle: {
            text: 'Total de votos por candidato'
        },
        xAxis: {
            categories: [
                'Candidatos',
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Cantidad de Votos'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} Votos</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: {{graph_votos_candidato|safe}},
    });
</script>

<script>
    Highcharts.chart('container3', {
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            },
            backgroundColor: '#f4f3f8',
        },
        title: {
            text: 'Elecciones de representantes 2021'
        },
        accessibility: {
            point: {
                valueSuffix: '%'
            }
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Votación',
            data: {{pie_votos_candidato|safe}}
        }]
    });
</script>
<!-- Graficas-->
<script>
    Highcharts.chart('container2', {
        chart: {
            type: 'column',
            backgroundColor: '#f4f3f8',
        },
        title: {
            text: 'Candidato / Representante'
        },
        accessibility: {
            announceNewData: {
                enabled: true
            }
        },
        xAxis: {
            type: 'category'
        },
        yAxis: {
            title: {
                text: 'Total Votos-Candidato'
            }

        },
        legend: {
            enabled: false
        },
        plotOptions: {
            series: {
                borderWidth: 0,
                dataLabels: {
                    enabled: true,
                    format: '{point.y:.1f}'
                }
            }
        },

        tooltip: {
            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}</b> of total<br/>'
        },

        series: [{
            name: "Candidatos",
            colorByPoint: true,
            data: {{graph_votos_candidato|safe}}
        }],
        drilldown: {
            series: {{graph_votos_hora_candidato|safe}}

        }
    });
</script>
<!-- Optional JavaScript; choose one of the two! -->
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
{% endblock content %}