votaciones/applications/users/urls.py
from django.urls import path

from . import views
app_name = 'users_app'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login-user'),
    path('logout/', views.LogoutView.as_view(), name='logout-user'),
]

votaciones/applications/votantes/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "votante_app"
urlpatterns = [
    path('bloqueo/', views.VerificarVotante.as_view(), name='verificacion-votante'),# se debe borrar el indexRaiz y dejar solo '' raiz
    path('eleccionCandidato/<cc>/', views.EleccionCandidato.as_view(), name='eleccion-votante'),
    path('error/', views.ErrorVotante.as_view(), name='error-votante'),
    path('agradecimiento/', views.agradecimientoVotante.as_view(), name='agradecimiento-votante'),
    path('reporte/', views.reporteVotacion.as_view(), name='reporte-votos'),
    path('reporte-directivo/', views.reporteVotacionDirectivo.as_view(), name='reporte-directivo'),
    path('reporte-administrativo/', views.reporteVotacionAdministrativo.as_view(), name='reporte-administrativo'),
    path('tabla/', views.TablaVotantesView.as_view(), name='tabla-votos'),
    path('', views.IndexTemporal.as_view(), name='temporal-index'), # esta se debe quitar, al momento de votar
]

votaciones/votaciones/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.votantes.urls')),
    path('', include('applications.users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

votaciones/applications/candidatos/models.py
from django.db import models
from applications.votantes.models import Votantes,tipo_candidato
from model_utils.models import TimeStampedModel
# Create your models here.


class Candidato(models.Model):
    nombre  = models.CharField(max_length=100)
    apellido  = models.CharField(max_length=100, null=True)
    cargo  = models.CharField(max_length=100,null=True)
    dependencia = models.CharField(max_length=100,null=True)
    foto = models.ImageField(("Foto Candidato"), upload_to='candidatos')
    tipo_candidato = models.ForeignKey(tipo_candidato, on_delete=models.CASCADE, related_name = 'candidate_tipo_candidato')
    num_tarjeton = models.IntegerField('Número del tarjetón', default=1)
    class Meta:
        verbose_name = "Candidato"
        verbose_name_plural = "Candidatos"

    def __str__(self):
        return self.nombre + ' - ' + self.apellido +  ' - ' + self.dependencia

class eleccion(TimeStampedModel):
    candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE,related_name='eleccion_to_candidate')
    votante = models.ForeignKey(Votantes,on_delete=models.CASCADE,unique=True)

    class Meta:
        verbose_name = "eleccion"
        verbose_name_plural = "elecciones"
        unique_together = ['candidato','votante']

    def __str__(self):
        return self.votante.nombre + ' - ' + str(self.votante.email) + ' - ' + str(self.votante.estado_voto)

votaciones/applications/candidatos/views.py
from django.shortcuts import render

# Create your views here.

votaciones/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {% load static %}
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'css/inputs.css' %}" />
    <link rel="stylesheet" href="{% static 'css/colors.css' %}" />
    <link rel="stylesheet" href="{% static 'css/eleccion.css' %}" />
    <link rel="stylesheet" href="{% static 'css/candidatos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/report.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/voters.css' %}" />
    <link rel="stylesheet" href="{% static 'css/scrollbar.css' %}" />


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" /> {% block head %} {% endblock head %}
    <title>{% block title %} {% endblock title %}</title>

    <style>
        @font-face {
            font-family: Photoshoot;
            src: local("Photoshoot"),
            url("{% static 'fonts/Photoshoot/PHOTOSHOOT.OTF'  format('truetype')' %}");
        }
        
        @font-face {
            font-family: Montserrat;
            font-weight: normal;
            src: local("Montserrat"),
            url("{% static 'fonts/Montserrat/Montserrat-Regular.ttf' format('truetype')' %}");
        }
        
        @font-face {
            font-family: Montserrat;
            font-weight: 900;
            src: local("Montserrat"),
            url("{% static 'fonts/Montserrat/Montserrat-Black.ttf'  format('truetype')' %}");
        }
        
        @font-face {
            font-family: Montserrat;
            font-weight: 800;
            src: local("Montserrat"),
            url("{% static 'fonts/Montserrat/Montserrat-Bold.ttf'  format('truetype')' %}");
        }
        
        @font-face {
            font-family: Montserrat;
            font-weight: 600;
            src: local("Montserrat"),
            url("{% static 'fonts/Montserrat/Montserrat-SemiBold.ttf'  format('truetype')' %}");
        }
        
        @font-face {
            font-family: Quicksand;
            src: local("Quicksand"),
            url("{% static 'fonts/Quicksand/Quicksand-VariableFont_wght.ttf'  format('truetype')' %}");
        }
    </style>
</head>

<body>
    {% block content %} {% endblock content %}
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

votaciones/templates/candidatos.html
{% extends "base.html" %} {% block title %} Elección de Candidato {% endblock title %} {% block content %} {% load static %} {% if mensaje %}
<h1>El usuario no cuenta con las credenciales necesarias, por favor redirigirse a la pagina de verificación de cedula</h1>
{% else %}

<div id="a-candidates-container">
    <nav class="navbar navbar-dark">
        <div class="container-fluid">
            {% load static %}
            <img src="{% static 'images/logo/villavo-white.svg' %}" alt=" " height="30" />
        </div>
    </nav>
    <div id="a-candidates-content">
        <div id="a-election-title">
            <h6>Tarjetón {{user.tipo_candidato}}</h6>
        </div>
        <div id="a-form-container">
            <form method="post" name="eleccion">
                {% csrf_token %}
                <input type="hidden" id="cc" name="cc" value="{{user.cedula}}" readonly="readonly"></input>
                <div id="a-candidates-main-container">
                    {% for c in candidatos %}
                    
                    <div class="a-candidate-info">
                        <div class="a-candidate-img">
                            <img src="{{c.foto.url}}" class="card-img-top" alt="... ">
                            <button type="submit " class="a-main-btn" onclick="valueRadio('{{c.id}}')">Votar</button>
                        </div>
                        <div class="a-candidate-desc">
                            <div class="a-candidate"><h3># Tarjetón {{c.num_tarjeton}} </h3></div>
                            <div class="a-candidate-name">{{c.nombre}} </div>
                            <div class="a-candidate-name">{{c.apellido}} </div>
                            <div class="a-candidate-other">{{c.cargo}}</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </div>
    <input type="hidden" id="candi" name="candi" value=" ">
    </form>
</div>
<script>
    function valueRadio(id) {
        document.eleccion.candi.value = id
    }
</script>
{% endif %} {% endblock content %}

votaciones/templates/eleccion.html
{% extends "base.html" %} {% block content %}

<div id="a-eleccion-container">
    {% load static %}
    <img src="{% static 'images/main.png' %}" alt="" id="a-background-img" />
    <div id="a-eleccion-content">
        <nav class="navbar navbar-dark">
            <div class="container-fluid">
                {% load static %}
                <img src="{% static 'images/logo/villavo-white.svg' %}" alt="" id="a-logo-img" />
                <form class="d-flex">
                    <a href="{% url 'users_app:login-user' %}" class="a-secondary-btn" type="button">
            Iniciar sesión
          </a>
                </form>
            </div>
        </nav>

        <div id="a-row">
            <div id="a-top-row">
                {% load static %}
                <img src="{% static 'images/figure-main.svg' %}" />
                <div id="a-subtitle">
                    <span>Elección de Representantes al Comité de
            Convicencia Laboral</span
          >
          <div id="a-rounded-rectangle"><span>Vigencia 2022-2024</span></div>
            </div>
        </div>
        <div id="a-bottom-row">
            <h5>Ingresa los datos para validar tu votación</h5>
            <form method="post">
                <div id="a-inputs-container">{% csrf_token %} {{form.as_p}}</div>
                <button class="a-main-btn" type="submit">Siguiente</button>
            </form>

            {% load static %}
            <img src="{% static 'images/good-treat.svg' %}" id="a-good-treat" />
        </div>
    </div>

    <div id="a-footer">
        Desarrollado por la Dirección de Sistemas Tecnológicos e Informáticos
        <br /> Secretaria de las TIC - Villavicencio Cambia Contigo
    </div>
</div>
</div>

{% endblock content %}

votaciones/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/colors.css' %}" />

    <style>
      html,
      body {
        height: 100%;
        width: 100%;
        margin: 0;
      }
      #a-error-container {
        margin: 0;
        height: 100%;
        width: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: var(--color-1);
        flex-flow: column nowrap;
      }
      #a-white-container {
        background-color: white;
        border-radius: 20px;
        color: var(--text-color);
        display: flex;
        flex-flow: column nowrap;
        justify-content: center;
        align-items: center;
        min-height: 200px;
        padding: 40px;
      }
      h3 {
        color: var(--color-2);
        font-family: Quicksand;
        font-size: 22px;
        font-weight: 900;
        margin: 0 0 10px 0;
      }
      .a-main-btn {
        width: 120px;
        height: 30px;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        text-decoration: none;
      }
    </style>
  </head>

  <body>
    <div id="a-error-container">
      <div id="a-white-container">
        <h3>Ha ocurrido un error</h3>
        <br />
        <span> {{message_error}} </span>
        <span>Comunícate con nosotros o inténtalo de nuevo.</span>
        <br />
        <a
          href="{% url 'votante_app:verificacion-votante' %}"
          class="a-main-btn"
          type="button"
        >
          Continuar
        </a>
      </div>
      <br />
      {% load static %}
      <img
        src="{% static 'images/logo/villavo-white.svg' %}"
        alt=""
        height="50"
      />
    </div>
  </body>
</html>

votaciones/templates/gracias.html
{% block content %}

<div id="a-thanks-container">
  {% load static %}
  <img src="{% static 'images/smile.svg' %}" alt=" " />
  <img src="{% static 'images/thanks.svg' %}" alt=" " />
</div>

<style>
  #a-thanks-container {
    background-color: rgba(3, 13, 33, 0.91);
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  body {
    margin: 0;
  }
</style>

{% endblock content %}

<script>
  setTimeout(() => {
    window.location.replace("{% url 'votante_app:verificacion-votante' %}");
  }, 2000);
</script>

votaciones/templates/temporal.html
{% extends "base.html" %} {% block content %}

<div id="a-eleccion-container">
    {% load static %}
    <img src="{% static 'images/main.png' %}" alt="" id="a-background-img" />
    <div id="a-eleccion-content">
        <nav class="navbar navbar-dark">
            <div class="container-fluid">
                {% load static %}
                <img src="{% static 'images/logo/villavo-white.svg' %}" alt="" id="a-logo-img" />
                <form class="d-flex">
                </form>
            </div>
        </nav>

        <div id="a-row">
            <div id="a-top-row">
                {% load static %}
                <img src="{% static 'images/figure-main.svg' %}" />
                <div id="a-subtitle">
                    <span>Elección de Representantes al Comité de
                        Convicencia Laboral</span
          >
          <div id="a-rounded-rectangle"><span>Vigencia 2022-2024</span></div>
            </div>
        </div>
        <div id="a-bottom-row">
            <h5>Las Votaciones Serán Habilitadas el día 27 de Octubre del 2022 de 8:00 am - 4:00 pm </h5>

            {% load static %}
            <img src="{% static 'images/good-treat.svg' %}" id="a-good-treat" />
        </div>
    </div>

    <div id="a-footer">
        Desarrollado por la Dirección de Sistemas Tecnológicos e Informáticos
        <br /> Secretaria de las TIC - Villavicencio Cambia Contigo
    </div>
</div>
</div>

{% endblock content %}